apiVersion: apps/v1
kind: Deployment
metadata:
  name: web                  # Mantemos o nome 'web' para ele atualizar o atual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: go-app
          image: vgip88/aula-primeira-pipeline:v17  # <--- SUA imagem aqui
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web                 # Aponta para o app: web do Deployment acima
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

